events {
    worker_connections 1024;
}

http {
    log_format upstream_logging '[$time_local] $remote_addr to $upstream_addr: "$request" $status';
    access_log /var/log/nginx/access.log upstream_logging;

    upstream web_servers {
        server web-frontend-server;
        server web-frontend-server1;
        server web-frontend-server2;
    }

    server {
        listen 80;
        
        # Docker internal DNS resolver
        resolver 127.0.0.11 valid=5s;

        # Route cho Web Frontend (Load Balancing)
        location / {
            set $frontend_upstream web_servers;
            proxy_pass http://$frontend_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Mapping cho bài Lab: Proxy /api/student -> Backend /student
        location /api/student {
            set $backend_upstream application-backend-server;
            proxy_pass http://$backend_upstream:8081/student;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route cho App API (students-db, students-json, hello)
        location /api {
            set $backend_upstream application-backend-server;
            proxy_pass http://$backend_upstream:8081;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route cho Keycloak Auth
        location /auth/ {
            set $auth_upstream authentication-identity-server;
            proxy_pass http://$auth_upstream:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
