events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Route cho Web Frontend
        location / {
            proxy_pass http://web-frontend-server:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route cho App API
        location /api/ {
            proxy_pass http://application-backend-server:8081/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route cho Keycloak Auth
        location /auth/ {
            proxy_pass http://authentication-identity-server:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
